GTG_MINIMAL_IDENTITY       = 0.57   # empirically choosen based on
                                    # _statistics/gtgstatistics.txt
GTG_MINIMAL_WEAKESTNODE    = 0.725  # empirically choosen based on
                                    # _statistics/gtgstatistics.txt

GTG_MINIMAL_IDENTITY_RANGE = (0.50,1.00)
GTG_MINIMAL_IDENTITY_MINVAL = GTG_MINIMAL_IDENTITY_RANGE[0]
GTG_MINIMAL_IDENTITY_MAXVAL = GTG_MINIMAL_IDENTITY_RANGE[1]
GTG_MINIMAL_IDENTITY_MINVAL_STRREPR = "%1.2f" % (
    GTG_MINIMAL_IDENTITY_MINVAL )
GTG_MINIMAL_IDENTITY_MAXVAL_STRREPR = "%1.2f" % (
    GTG_MINIMAL_IDENTITY_MAXVAL )


GTG_MINIMAL_WEAKESTNODE_RANGE = (0.67,0.82)
GTG_MINIMAL_WEAKESTNODE_MINVAL = GTG_MINIMAL_WEAKESTNODE_RANGE[0]
GTG_MINIMAL_WEAKESTNODE_MAXVAL = GTG_MINIMAL_WEAKESTNODE_RANGE[1]
GTG_MINIMAL_WEAKESTNODE_MINVAL_STRREPR = "%1.2f" % (
    GTG_MINIMAL_WEAKESTNODE_MINVAL )
GTG_MINIMAL_WEAKESTNODE_MAXVAL_STRREPR = "%1.2f" % (
    GTG_MINIMAL_WEAKESTNODE_MAXVAL )

 
